# https://slashgear.github.io/how-to-deploy-on-github-pages-with-travis-ci/

language: ruby
rvm:
- 2.3.3

bundle exec jekyll build
touch ./_site/.nojekyll # this file tells gh-pages that there is no need to build

deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: _site
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: master
  on:
    # Which branch on commit/push will trigger deployment
    branch: master