# replicate github-pages's defaults / overrides
name: Associated Students of Linguistics
permalink: pretty

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
gems:
  - jekyll-coffeescript
  - jekyll-paginate
